FUNCTION Z_TR_CAJA_OPER_CLONE_DOC.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     REFERENCE(BUKRS) TYPE  BUKRS
*"     REFERENCE(BELNR) TYPE  BELNR_D
*"     REFERENCE(GJAHR) TYPE  GJAHR
*"  TABLES
*"      TZFIES_EX_IT_RETURN STRUCTURE  ZFIES_EX_IT_RETURN
*"----------------------------------------------------------------------
  DATA:
    ZFIES_PAYLIQADV     TYPE  ZFIES_PAYLIQADV,
    TZFIES_IMITPOSITION TYPE STANDARD TABLE OF ZFIES_IMITPOSITION,
    WZFIES_IMITPOSITION TYPE ZFIES_IMITPOSITION,
    WITH_ITEM           TYPE WITH_ITEM,
    WZFIES_EX_IT_RETURN TYPE ZFIES_EX_IT_RETURN,
    ZTR_COPER_HEADER    type ZTR_COPER_HEADER,
    TZTR_COPER_POS      type STANDARD TABLE OF ZTR_COPER_POS,
    WZTR_COPER_POS      type ZTR_COPER_POS,
    EX_STATUS           type char1.

  select single * from ZTR_COPER_HEADER
    into ZTR_COPER_HEADER
    where IM_BUKRS = bukrs and
          IM_BELNR = belnr and
          IM_GJAHR = gjahr.

  select * from ZTR_COPER_POS
    into TABLE TZTR_COPER_POS
    where UUID = ZTR_COPER_HEADER-UUID.

  clear: ZFIES_PAYLIQADV,
         TZFIES_IMITPOSITION,
         WZFIES_IMITPOSITION,
         TZFIES_EX_IT_RETURN.

  move-CORRESPONDING ZTR_COPER_HEADER to ZFIES_PAYLIQADV.
  clear TZFIES_IMITPOSITION.
  loop at TZTR_COPER_POS into WZTR_COPER_POS.
    move-CORRESPONDING WZTR_COPER_POS TO WZFIES_IMITPOSITION.
    append WZFIES_IMITPOSITION to TZFIES_IMITPOSITION.
  endloop.


  if TZFIES_IMITPOSITION is not INITIAL.

    CALL FUNCTION 'ZMFFI_POLIZA_CONTABLE'
      EXPORTING
        ZFIES_PAYLIQADV    = ZFIES_PAYLIQADV
      IMPORTING
        EX_STATUS          = EX_STATUS
      TABLES
        ZFIES_IMITPOSITION = TZFIES_IMITPOSITION
        ZFIES_EX_IT_RETURN = TZFIES_EX_IT_RETURN.

  endif.

ENDFUNCTION.
